# Basic lists of Spanish regions, provinces, and major cities.
# These are used to populate dropdowns in forms when the
# ``cities_light`` database tables are unavailable. The values
# correspond to the most common names in Spanish.

# Autonomous communities + autonomous cities
REGION_CHOICES = [
    ("Andalucía", "Andalucía"),
    ("Aragón", "Aragón"),
    ("Asturias", "Asturias"),
    ("Islas Baleares", "Islas Baleares"),
    ("Canarias", "Canarias"),
    ("Cantabria", "Cantabria"),
    ("Castilla-La Mancha", "Castilla-La Mancha"),
    ("Castilla y León", "Castilla y León"),
    ("Cataluña", "Cataluña"),
    ("Comunidad Valenciana", "Comunidad Valenciana"),
    ("Extremadura", "Extremadura"),
    ("Galicia", "Galicia"),
    ("Madrid", "Madrid"),
    ("Murcia", "Murcia"),
    ("Navarra", "Navarra"),
    ("País Vasco", "País Vasco"),
    ("La Rioja", "La Rioja"),
    ("Ceuta", "Ceuta"),
    ("Melilla", "Melilla"),
]

# Provinces (including autonomous cities)
PROVINCE_CHOICES = [
    ("Álava", "Álava"),
    ("Albacete", "Albacete"),
    ("Alicante", "Alicante"),
    ("Almería", "Almería"),
    ("Asturias", "Asturias"),
    ("Ávila", "Ávila"),
    ("Badajoz", "Badajoz"),
    ("Barcelona", "Barcelona"),
    ("Burgos", "Burgos"),
    ("Cáceres", "Cáceres"),
    ("Cádiz", "Cádiz"),
    ("Cantabria", "Cantabria"),
    ("Castellón", "Castellón"),
    ("Ciudad Real", "Ciudad Real"),
    ("Córdoba", "Córdoba"),
    ("Cuenca", "Cuenca"),
    ("Girona", "Girona"),
    ("Granada", "Granada"),
    ("Guadalajara", "Guadalajara"),
    ("Guipúzcoa", "Guipúzcoa"),
    ("Huelva", "Huelva"),
    ("Huesca", "Huesca"),
    ("Islas Baleares", "Islas Baleares"),
    ("Jaén", "Jaén"),
    ("La Coruña", "La Coruña"),
    ("La Rioja", "La Rioja"),
    ("Las Palmas", "Las Palmas"),
    ("León", "León"),
    ("Lérida", "Lérida"),
    ("Lugo", "Lugo"),
    ("Madrid", "Madrid"),
    ("Málaga", "Málaga"),
    ("Murcia", "Murcia"),
    ("Navarra", "Navarra"),
    ("Orense", "Orense"),
    ("Palencia", "Palencia"),
    ("Pontevedra", "Pontevedra"),
    ("Salamanca", "Salamanca"),
    ("Santa Cruz de Tenerife", "Santa Cruz de Tenerife"),
    ("Segovia", "Segovia"),
    ("Sevilla", "Sevilla"),
    ("Soria", "Soria"),
    ("Tarragona", "Tarragona"),
    ("Teruel", "Teruel"),
    ("Toledo", "Toledo"),
    ("Valencia", "Valencia"),
    ("Valladolid", "Valladolid"),
    ("Vizcaya", "Vizcaya"),
    ("Zamora", "Zamora"),
    ("Zaragoza", "Zaragoza"),
    ("Ceuta", "Ceuta"),
    ("Melilla", "Melilla"),
]

# Major cities (mostly provincial capitals)
CITY_CHOICES = [
    ("Vitoria-Gasteiz", "Vitoria-Gasteiz"),
    ("Albacete", "Albacete"),
    ("Alicante", "Alicante"),
    ("Almería", "Almería"),
    ("Oviedo", "Oviedo"),
    ("Ávila", "Ávila"),
    ("Badajoz", "Badajoz"),
    ("Barcelona", "Barcelona"),
    ("Burgos", "Burgos"),
    ("Cáceres", "Cáceres"),
    ("Cádiz", "Cádiz"),
    ("Santander", "Santander"),
    ("Castellón de la Plana", "Castellón de la Plana"),
    ("Ciudad Real", "Ciudad Real"),
    ("Córdoba", "Córdoba"),
    ("Cuenca", "Cuenca"),
    ("Girona", "Girona"),
    ("Granada", "Granada"),
    ("Guadalajara", "Guadalajara"),
    ("San Sebastián", "San Sebastián"),
    ("Huelva", "Huelva"),
    ("Huesca", "Huesca"),
    ("Palma de Mallorca", "Palma de Mallorca"),
    ("Jaén", "Jaén"),
    ("A Coruña", "A Coruña"),
    ("Logroño", "Logroño"),
    ("Las Palmas de Gran Canaria", "Las Palmas de Gran Canaria"),
    ("León", "León"),
    ("Lleida", "Lleida"),
    ("Lugo", "Lugo"),
    ("Madrid", "Madrid"),
    ("Málaga", "Málaga"),
    ("Murcia", "Murcia"),
    ("Pamplona", "Pamplona"),
    ("Ourense", "Ourense"),
    ("Palencia", "Palencia"),
    ("Pontevedra", "Pontevedra"),
    ("Salamanca", "Salamanca"),
    ("Santa Cruz de Tenerife", "Santa Cruz de Tenerife"),
    ("Segovia", "Segovia"),
    ("Sevilla", "Sevilla"),
    ("Soria", "Soria"),
    ("Tarragona", "Tarragona"),
    ("Teruel", "Teruel"),
    ("Toledo", "Toledo"),
    ("Valencia", "Valencia"),
    ("Valladolid", "Valladolid"),
    ("Bilbao", "Bilbao"),
    ("Zamora", "Zamora"),
    ("Zaragoza", "Zaragoza"),
    ("Ceuta", "Ceuta"),
    ("Melilla", "Melilla"),
]
