# Generated by Django 5.1.2 on 2025-05-01 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/logos/')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('club', 'Club'), ('entrenador', 'Entrenador'), ('promotor', 'Promotor'), ('servicio', 'Servicio')], default='club', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.FileField(blank=True, null=True, upload_to='features/')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='ClubPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='club_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('titulos', models.TextField(blank=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competidores', to='clubs.club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='features',
            field=models.ManyToManyField(blank=True, to='clubs.feature'),
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('instalaciones', models.PositiveIntegerField()),
                ('entrenadores', models.PositiveIntegerField()),
                ('ambiente', models.PositiveIntegerField()),
                ('calidad_precio', models.PositiveIntegerField()),
                ('variedad_clases', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='clubs.club')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
