# Generated by Django 4.2.20 on 2025-05-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
