# Generated by Django 5.1.2 on 2025-05-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_reseña_stars_alter_reseña_ambiente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='variedad_clases',
            new_name='adaptabilidad_clases',
        ),
    ]
