# Generated by Django 4.2.20 on 2025-05-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_horario_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
