# Generated by Django 5.1.2 on 2025-05-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_rename_variedad_clases_reseña_adaptabilidad_clases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='adaptabilidad_clases',
            new_name='variedad_clases',
        ),
    ]
