# Generated by Django 4.2.20 on 2025-05-25 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_horario_hora_fin_alter_horario_hora_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['dia']},
        ),
        migrations.AddField(
            model_name='horario',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('competicion', 'Competición'), ('vacaciones', 'Vacaciones')], default='abierto', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('club', 'dia')},
        ),
        migrations.CreateModel(
            name='FranjaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('nota', models.CharField(blank=True, default='', max_length=30)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franjas', to='clubs.horario')),
            ],
            options={
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.RemoveField(
            model_name='horario',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='hora_inicio',
        ),
    ]
