# Generated by Django 4.2.20 on 2025-05-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_horario_options_horario_estado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
    ]
