# Generated by Django 5.1.2 on 2025-05-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_rename_adaptabilidad_clases_reseña_variedad_clases'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
