# Generated by Django 5.1.2 on 2025-06-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0008_clubpost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clubpost",
            options={"ordering": ["-created_at"]},
        ),
    ]
