# Generated by Django 5.1.2 on 2025-06-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0009_alter_clubpost_options"),
        ("clubs", "0009_booking"),
    ]

    operations = []
