# Generated by Django 5.1.2 on 2025-06-20 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_clubpost_threads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_clubposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
