# Generated by Django 5.1.2 on 2025-06-25 00:00
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_clubpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=7),
        ),
        migrations.AddField(
            model_name='horario',
            name='nota',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
