# Generated by Django 5.1.2 on 2025-07-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0023_pago_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='clase',
        ),
        migrations.AlterModelOptions(
            name='clubphoto',
            options={'ordering': ['-is_main', 'uploaded_at']},
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
    ]
