# Generated by Django 5.1.2 on 2025-07-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0024_miembro_extra_fields'),
        ('clubs', '0024_remove_booking_clase_alter_clubphoto_options_and_more'),
    ]

    operations = [
    ]
