# Generated by Django 5.1.2 on 2025-07-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_merge_20250715_0837'),
        ('clubs', '0025_miembro_location'),
    ]

    operations = [
    ]
