# Generated by Django 5.1.2 on 2025-07-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0032_booking_class_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingclass',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Duración en minutos'),
        ),
    ]
