# Generated by Django 5.1.2 on 2025-08-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0036_clubmessage_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="plan",
            field=models.CharField(
                choices=[
                    ("bronce", "Plan Bronce"),
                    ("plata", "Plan Plata"),
                    ("oro", "Plan Oro"),
                ],
                default="bronce",
                max_length=20,
            ),
        ),
    ]
