# Generated by Django 5.1.2 on 2025-08-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0038_remove_club_whatsapp_link_club_country_club_door_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="miembro",
            name="direccion",
        ),
        migrations.AddField(
            model_name="club",
            name="prefijo",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="miembro",
            name="prefijo",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="club",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
