# Generated by Django 5.1.2 on 2025-08-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0040_alter_club_country_alter_miembro_nacionalidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="bookmarked_competidores",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarked_por_clubes", to="clubs.competidor"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[("España", "España")],
                default="España",
                max_length=100,
            ),
        ),
    ]
