# Generated by Django 5.1.2 on 2025-02-15 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0041_club_bookmarked_competidores_alter_club_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrenador",
            name="perfil_publico",
            field=models.BooleanField(default=True, verbose_name="Perfil público"),
        ),
    ]
