# Generated by Django 5.1.2 on 2025-08-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0041_club_bookmarked_competidores_alter_club_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="miembro",
            name="codigo",
            field=models.CharField(
                blank=True, editable=False, max_length=7, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="miembro",
            name="fuente",
            field=models.CharField(
                blank=True,
                choices=[
                    ("directa", "Directa"),
                    ("presencial", "Presencial"),
                    ("telefono", "Telefono"),
                    ("otros", "Otros"),
                ],
                max_length=20,
            ),
        ),
    ]
