# Generated by Django 5.1.2 on 2025-08-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0042_miembro_codigo_miembro_fuente"),
    ]

    operations = [
        migrations.AddField(
            model_name="miembro",
            name="door",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="miembro",
            name="number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="miembro",
            name="region",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="miembro",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
