# Generated by Django 5.1.2 on 2025-08-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0043_miembro_door_miembro_number_miembro_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='guardia',
            field=models.CharField(blank=True, choices=[('diestro', 'Diestro'), ('zurdo', 'Zurdo')], max_length=7),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado',
            field=models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10, null=True),
        ),
    ]
