# Generated by Django 5.1.2 on 2025-08-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0044_miembro_guardia_alter_miembro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='guardia',
            field=models.CharField(blank=True, choices=[('diestro', 'Diestro'), ('zurdo', 'Zurdo'), ('ambidiestro', 'Ambidiestro')], max_length=11),
        ),
    ]
