# Generated by Django 5.1.2 on 2025-08-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0045_alter_miembro_guardia"),
    ]

    operations = [
        migrations.AddField(
            model_name="competidor",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
