# Generated by Django 5.1.2 on 2025-08-14 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0046_competidor_fecha_nacimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="clubs.clubmessage",
            ),
        ),
    ]
