# Generated by Django 5.1.2 on 2025-08-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0048_clubchat"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="profilepic",
            field=models.ImageField(
                blank=True, null=True, upload_to="clubs/profilepics/"
            ),
        ),
    ]
