# Generated by Django 5.1.2 on 2025-08-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0049_club_profilepic"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.FileField(
                        blank=True, null=True, upload_to="coach_features/"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="club",
            name="coach_features",
            field=models.ManyToManyField(blank=True, to="clubs.coachfeature"),
        ),
        migrations.AddField(
            model_name="entrenador",
            name="features",
            field=models.ManyToManyField(blank=True, to="clubs.coachfeature"),
        ),
    ]
