# Generated by Django 5.1.2 on 2025-05-05 00:01
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_object_id', models.PositiveIntegerField()),
                ('followed_object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('followed_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_followed', to='contenttypes.contenttype')),
                ('follower_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_follower', to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('follower_content_type', 'follower_object_id', 'followed_content_type', 'followed_object_id')},
            },
        ),
    ]
