# Generated by Django 5.1.2 on 2025-08-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="plan",
            field=models.CharField(
                choices=[
                    ("bronce", "Plan Bronce"),
                    ("plata", "Plan Plata"),
                    ("oro", "Plan Oro"),
                ],
                default="bronce",
                max_length=10,
            ),
        ),
    ]
