# Generated by Django 5.1.2 on 2025-08-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_type",
            field=models.CharField(
                choices=[("club_owner", "Club Owner"), ("coach", "Coach")],
                default="club_owner",
                max_length=20,
            ),
        ),
    ]
